### PR TITLE
Myeloid panel

### PR DESCRIPTION
**Pull request by erikwaskiewicz**
## Change description
- Add bed files for myeloid, CLL and MPN panels
- Update `vendorCaptureBed_100pad_updated.bed` and `TSO_extra_padding_chr.interval_list` so that they both include these regions
- Added script to pull through selected variants that were previously filtered by the blacklist (and new environment called pysam to run it in, it clashed with the Python version in the `TSO500_post_processing` env)

## Justification for minor update
No effect on sensitivity

## Testing description
Verified in CC-22-193-GEN

Pipeline was run end to end in `/Output/validations/TSO500/myeloid_test_run/`
- Check that virtual panels were applied correctly and upload to the database
- Check that blacklisted variants were pulled through as expected
- Check VAF is within the validated rage from TSO500 in reference standards
- Check difference in transcripts

## Test data location
`/Output/validations/TSO500/myeloid_test_run/`

`S:\MedGen\SHARED\Lab Genetics\TECHNICAL SECTION\NGS & Sequencing\Developmental work\NovaSeq\Validation_Projects\Comprehensive Cancer Panel\CC-22-193 Myeloid`

## Verification results
Pipeline run through successfully and all tests passed. Results are included in the writeup for CC-22-193-GEN

### CODE REVIEW

**Comment by erikwaskiewicz** [comment]
@LauraMcCluskey7 - bed files have already been checked by the clinical scientists, only the changes in the `scripts` and `env` folders need reviewing

**Comment by LauraMcCluskey7** [comment]
The variant frequency value extracted from the vcf isn't exact due to float being used in the vcf header. The fix for this would be to change the type in the vcf header to string, then convert to a decimal in the script.

**Comment by erikwaskiewicz** [comment]
> The variant frequency value extracted from the vcf isn't exact due to float being used in the vcf header. The fix for this would be to change the type in the vcf header to string, then convert to a decimal in the script.

This has been fixed in the last commit

> It would also be good to have unittests for this script to make it easier for changes to be made in the future

Agree but given timeframes it'll have to be done in future. I've added an issue (#34)


@LauraMcCluskey7 can you review the last commit please and sign off the review if you're happy

**Review by LauraMcCluskey7 — APPROVED** [review]
I'm happy with the changes made and have now approved for the myeloid branch to be merged with development

**Pull request merged**
